### ISSUE TITLE
Proposal: Value Type Kernels

### ISSUE THREAD

**Issue by antonfirsov** [JimBobSquarePants/ImageSharp#142]
### Prerequisites
- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have searched [open](https://github.com/JimBobSquarePants/ImageSharp/issuess) and [closed](https://github.com/JimBobSquarePants/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### The problem
- There are many places in the library where we operate on relatively small matrices known at compile time using a dynamically allocated heap array (wrapped in `Fast2DArray`):
  - `ConvolutionProcessor`-s 
  - `PatternBrush`-es
  - `ResizeProcessor` weight windows
- This approach bings in implicit overhead, having a significant negative effect on performance:
  - Indexing heap arrays increases the probabilty of cache misses
  - Calculations are iterating using nested for loops instad of having a simple expression

### The solution
- Define `KernelMatrix*x*` structures for common kernel sizes (Like `KernelMatrix4x3`, `KernelMatrix4x1` etc.)
- Use specific kernel matrix structures (known at compile time!) as a generic arguments in implementation related classes (`ConvolutionProcessor<TColor, TKernelMatrix>` !)
  - Using `KernelMatrix9x1`-like constructs as resampler windows could bring significant performance improvements for ResizeProcessor (see #139) too!
- Implement all kernel-related calculations as simple expressions without for loops, etc (Like implementations of `Matrix4x4`)
- Use a generic matrix for unknown sizes (something like `Fast2DArray<float>`)

### TODO
- [ ] Prototype a benchmark comparing a heap matrix VS a value matrix convolution
- [ ] Implement stuff based on benchmark conclusions

**Comment by JimBobSquarePants** [comment]
@antonfirsov I think we should try and make this a priority now if we're gonna get it in for V1.

**Comment by antonfirsov** [comment]
@JimBobSquarePants hmm .. originally I wanted to polish + standardize our memory management in the next few months, but there are many uncertainties around that topic, so maybe I'll grab this one instead.

There is a lot of work here though, but maybe we can make it into 1.0.

**Comment by JimBobSquarePants** [comment]
@antonfirsov Have a look and estimate it then. Looking at it myself I'm envisaging quite a lot of API changes to allow it which makes me think maybe it's for V2 instead.

**Comment by JimBobSquarePants** [comment]
This issue has been open for a long time and the original proposal no longer reflects how ImageSharp has evolved.

While the idea of fixed-size, value-type kernels can make sense in principle, kernel storage and access have not proven to be a meaningful performance bottleneck in practice. Modern convolution performance is dominated by pixel access patterns, memory bandwidth, border handling, SIMD utilization, and the use of separable kernels, rather than how small kernel matrices are represented.

The library now uses a value-typed matrix abstraction, and any future performance work in this area would need to be driven by current benchmarks and likely take a different form (for example, size-based fast paths or separable kernel specialization), not the generic fixed-size matrix types proposed here in 2017.

For these reasons, this issue is being closed. If someone can demonstrate, with up-to-date benchmarks, that kernel representation is a real bottleneck today, a new issue with concrete data and a modern proposal would be the right place to discuss it.
